spring.application.name=DemoStudent
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.sql.init.username=postgres.dlaupbmsicnhgvriaidj
spring.datasource.password=Pranav@0901
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update